"""Data-driven unit and building definitions.

Adding a new entity = one dict entry here + pixel art in rts_sprites.py.
"""

UNIT_DEFS = {
    # ── Human ──
    "engineer": {
        "faction": "human",
        "hp": 30,
        "speed": 1.5,
        "attack": 0,
        "attack_range": 0,
        "cost": {"crystals": 100, "isotope": 0},
        "can_build": True,
        "can_harvest": False,
        "vision": 5,
        "size": (1, 1),
    },
    "miner": {
        "faction": "human",
        "hp": 35,
        "speed": 1.2,
        "attack": 0,
        "attack_range": 0,
        "cost": {"crystals": 50, "isotope": 0},
        "can_build": False,
        "can_harvest": True,
        "harvest_rate": 10,
        "carry_capacity": 50,
        "isotope_harvest_rate": 10,
        "isotope_carry_capacity": 25,
        "vision": 4,
        "size": (1, 1),
    },
    "marine": {
        "faction": "human",
        "hp": 60,
        "speed": 1.8,
        "attack": 6,
        "attack_range": 5,
        "cost": {"crystals": 75, "isotope": 25},
        "can_build": False,
        "can_harvest": False,
        "vision": 6,
        "size": (1, 1),
    },
    "scout_human": {
        "faction": "human",
        "hp": 40,
        "speed": 2.2,
        "attack": 0,
        "attack_range": 0,
        "cost": {"crystals": 20, "isotope": 0},
        "can_build": False,
        "can_harvest": False,
        "vision": 8,
        "size": (1, 1),
    },
    "drone": {
        "faction": "lizard",
        "hp": 25,
        "speed": 1.2,
        "attack": 0,
        "attack_range": 0,
        "cost": {"crystals": 75, "isotope": 0},
        "can_build": False,
        "can_harvest": True,
        "harvest_rate": 10,
        "carry_capacity": 50,
        "isotope_harvest_rate": 10,
        "isotope_carry_capacity": 25,
        "vision": 4,
        "size": (1, 1),
    },
    # ── Cyber Lizard ──
    "scout": {
        "faction": "lizard",
        "hp": 35,
        "speed": 1.8,
        "attack": 4,
        "attack_range": 1,
        "cost": {"crystals": 80, "isotope": 10},
        "can_build": False,
        "can_harvest": False,
        "vision": 6,
        "size": (1, 1),
    },
    "warrior": {
        "faction": "lizard",
        "hp": 80,
        "speed": 1.0,
        "attack": 12,
        "attack_range": 1,
        "cost": {"crystals": 150, "isotope": 60},
        "can_build": False,
        "can_harvest": False,
        "vision": 4,
        "size": (1, 1),
    },
    "spitter": {
        "faction": "lizard",
        "hp": 40,
        "speed": 1.2,
        "attack": 7,
        "attack_range": 5,
        "cost": {"crystals": 120, "isotope": 50},
        "can_build": False,
        "can_harvest": False,
        "vision": 6,
        "size": (1, 1),
    },
}

BUILDING_DEFS = {
    # ── Human ──
    "main_base": {
        "faction": "human",
        "hp": 500,
        "cost": {"crystals": 400, "isotope": 100},
        "size": (3, 3),
        "produces": ["engineer", "miner", "scout_human"],
        "vision": 8,
        "crystal_capacity": 1000,
        "isotope_capacity": 500,
        "build_time": 600,  # 10 seconds at 60fps
        "max_count": 1,
    },
    "barracks": {
        "faction": "human",
        "hp": 300,
        "cost": {"crystals": 200, "isotope": 50},
        "size": (2, 2),
        "produces": ["marine"],
        "vision": 6,
    },
    "turret": {
        "faction": "human",
        "hp": 200,
        "cost": {"crystals": 150, "isotope": 25},
        "size": (1, 1),
        "produces": [],
        "attack": 10,
        "attack_range": 6,
        "vision": 7,
    },
    "mining_camp": {
        "faction": "human",
        "hp": 150,
        "cost": {"crystals": 100, "isotope": 0},
        "size": (2, 2),
        "produces": [],
        "vision": 4,
        "crystal_capacity": 250,
        "is_mining_camp": True,
    },
    "isotope_extractor": {
        "faction": "human",
        "hp": 150,
        "cost": {"crystals": 150, "isotope": 0},
        "size": (2, 2),
        "produces": [],
        "vision": 4,
        "isotope_capacity": 100,
        "is_isotope_camp": True,
    },
    # ── Cyber Lizard ──
    "hive": {
        "faction": "lizard",
        "hp": 500,
        "cost": {"crystals": 0, "isotope": 0},
        "size": (3, 3),
        "produces": ["drone", "scout"],
        "vision": 8,
        "crystal_capacity": 1000,
        "isotope_capacity": 500,
    },
    "war_pit": {
        "faction": "lizard",
        "hp": 300,
        "cost": {"crystals": 200, "isotope": 50},
        "size": (2, 2),
        "produces": ["warrior", "spitter"],
        "vision": 6,
    },
    "spine": {
        "faction": "lizard",
        "hp": 150,
        "cost": {"crystals": 150, "isotope": 40},
        "size": (1, 1),
        "produces": [],
        "attack": 10,
        "attack_range": 6,
        "vision": 7,
    },
    "isotope_siphon": {
        "faction": "lizard",
        "hp": 150,
        "cost": {"crystals": 150, "isotope": 0},
        "size": (2, 2),
        "produces": [],
        "vision": 4,
        "isotope_capacity": 100,
        "is_isotope_camp": True,
    },
}

# Mapping: building type -> which building can produce it
PRODUCED_BY = {}
for btype, bdef in BUILDING_DEFS.items():
    for utype in bdef.get("produces", []):
        PRODUCED_BY[utype] = btype
